#!/usr/bin/env bash
# Installs HAproxy load-balancer on a server
#Configures a new Ubuntu server with a HAproxy load-balancer
apt-get -y install software-properties-common
apt-get -y update
apt-get -y install haproxy=2.0.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend munalaerastus.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 117170-web-01 52.87.255.233:80 check
	server 117170-web-02 100.25.142.86:80 check
' >> /etc/haproxy/haproxy.cfg
sudo chmod +x /etc/init.d/haproxy

# Restart HAproxy service
service haproxy restart
